#!/usr/bin/env bash
# Regenerate src/KeepSymbols.hx — a static reference to every openfl-swf generated library symbol so
# Haxe DCE retains them (they are otherwise only referenced dynamically via Type.resolveClass(name),
# get stripped, and resolveClass returns null at runtime -> "can't find obj" / null graphic crashes).
# Run after a build has populated bin/html5/haxe/_generated/ (i.e. after the swf library is parsed).
set -euo pipefail
cd "$(dirname "$0")/.."
GEN=bin/html5/haxe/_generated
[ -d "$GEN" ] || { echo "ERROR: $GEN not found — run a build first" >&2; exit 1; }
python3 - "$GEN" > src/KeepSymbols.hx <<'PY'
import os, sys
d=sys.argv[1]; names=[]
for f in sorted(os.listdir(d)):
    if not f.endswith('.hx'): continue
    b=f[:-3]; txt=open(os.path.join(d,f)).read()
    if any(('class '+b+s) in txt for s in (' ','\n','(',' extends')): names.append(b)
print('// AUTO-GENERATED by tools/gen-keep-symbols.sh — do not edit by hand.')
print('// Static references to every openfl-swf generated symbol so Haxe DCE keeps them')
print('// (they are otherwise only resolved dynamically by name and get stripped).')
print('@:keep class KeepSymbols {')
print('    @:keep public static var symbols : Array<Class<Dynamic>> = [')
print('        ' + ',\n        '.join(names))
print('    ];')
print('}')
PY
echo "wrote src/KeepSymbols.hx ($(grep -c ',' src/KeepSymbols.hx) symbols)"
